### ISSUE TITLE
"publisher confirms" does not wait for acknowledgement from the consumer

### ISSUE THREAD

**Issue by beanefit** [CJWorkbench/carehare#4] opened 2021-07-21 10:22 UTC
I expect that `await connection.publish(message, routing_key)` completes only when the consumer sends the ack, but it completes right after the message is sent to the queue.

Is there a way to meet my expectations? Or maybe it is a bug?

**Comment by adamhooper** [comment] 2021-07-21 11:25
This is the AMQP spec: "confirmed" means the message has been written to disk on RabbitMQ. Closing as not a bug.

If you want an acknowledgement from the consumer, roll your own solution. Write some sort of address (e.g. host+port, queue+routing_key, token, etc.) in the message. Code the consumer to send a message to that address when it's done. Or when it's started. Or mid-completion. Whenever.

**Closed as completed by adamhooper** 2021-07-21 11:25 UTC
Labels: invalid
